apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yt09qj8vr-java-springboot
  janus-idp.io/tekton: yt09qj8vr-java-springboot
  backstage.io/kubernetes-id: yt09qj8vr-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yt09qj8vr-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
